// content.js — human-editable copy for the Bali 2026 pitch.
// Plain strings only. No HTML. Inline emphasis: **bold** and *italic* only.
// Titles may use \n for line breaks. Images are Wikimedia Commons FILENAMES only.

export default {
  meta: { title: "Bali 2026 — The Pitch" },
  sections: [
    {
      id: "hero",
      label: "Open",
      image: "Pura_Tanah_Lot.jpg",
      eyebrow: "Three weeks in the Island of the Gods",
      title: "BALI\n2026",
      body: "with Karl & Keshia",
      dates: "30 June – 20 July 2026",
    },
    {
      id: "arc",
      label: "The vibe",
      eyebrow: "Overall Plan",
      title: "Parties, Beaches, Mountains.",
      body: "Get on with the partying: beach clubs, late nights, then the beach dives, before going off into the jungle, mountains and Eat, Pray, Love.",
      arc: ["🔥 Party-forward", "🌊 Adventure", "🌴 Intimate & slow"],
      note: "Yes you'll get lots of Instagrammable places",
    },
    {
      id: "seminyak",
      label: "Seminyak",
      image: "Seminyak_Beach_Resort_Large.JPG",
      deco: "01",
      nights: "30 Jun – 1 Jul · landing",
      title: "First Night @ Seminyak",
      body: "Land at 9pm and fall into a bed. Day one is a soft-launch.",
      bullets: [
        "🛅 Find long-term luggage storage",
        "🛍️ Quick clothes shopping",
      ],
    },
    {
      id: "uluwatu",
      label: "Uluwatu",
      image: "Uluwatu_Temple_at_Sunset.jpg",
      deco: "02",
      nights: "1 – 3 Jul · 2 nights",
      title: "Uluwatu",
      body: "Clifftops over the Indian Ocean.",
      bullets: [
        "🔥 Kecak fire dance at sunset on the clifftop temple",
        "🏄 A first surf lesson at Padang Padang or Bingin",
        "🍽️ Dinner on the edge of the cliff, ocean roaring below",
        "🍹 Single Fin sundowners with the break underneath us",
      ],
    },
    {
      id: "canggu",
      label: "Canggu",
      image: "Sunset_at_Canggu_beach.jpg",
      deco: "03",
      nights: "3 – 6 Jul · 3 nights · Batu Bolong",
      title: "Canggu",
      body: "Digital nomad and Instagram central! Beach clubs, breakfast bowls, body building.",
      tags: [
        "🏋️ Fitness",
        "🥝 Açai Bowls",
        "🍸 Finns Beach Club",
        "🎸 Deus Ex Machina",
        "🌺 Pretty Poison",
      ],
    },
    {
      id: "nusa",
      label: "Nusa Islands",
      image: "Kelingking_Beach.jpg",
      deco: "04",
      nights: "6 – 9 Jul · 3 nights · based on Nusa Lembongan",
      title: "The Nusa Islands",
      body: "The postcard days. One day on Penida, one slow day island-hopping by the Yellow Bridge.",
      bullets: [
        "🦖 Kelingking Beach — the T-Rex cliff (yes, *that* shot)",
        "🌊 Broken Beach & Angel's Billabong loop",
        "🛶 Mangrove paddle through the channels on Lembongan",
      ],
      decision: {
        group: "manta",
        label: "Your call 🤿",
        question:
          "Penida is one of the few places you can swim with **manta rays** without a dive cert. Do we keep it to an easy snorkel — or go bigger?",
        options: [
          "Snorkel with the mantas",
          "Go bigger — let's try a dive",
          "Stay dry, just the views",
        ],
      },
    },
    {
      id: "east",
      label: "East Bali",
      image: "RICE_TERRACE_OF_SIDEMEN_EAST_BALI.jpg",
      deco: "05",
      nights: "9 – 12 Jul · ~3 nights · Sidemen",
      title: "East Bali — Sidemen",
      body: "The green, quiet valley. Rice terraces, a water palace, and a cooking class in a family compound.",
      bullets: [
        "💧 Tirta Gangga water palace day trip",
        "🌾 Morning rice-terrace walk before the heat",
        "🍳 Cook a Balinese meal with a local family",
      ],
      decision: {
        group: "amed",
        label: "Open question 🌊",
        question:
          "We could add **one night in Amed** on the way — snorkelling the *USAT Liberty* shipwreck right off the beach. It's a magic spot, but it's an extra travel leg. We could also meet up with Demi on Thursday and Friday.",
        options: [
          "Add Amed for the wreck",
          "Skip it — straight to Sidemen",
          "One more party weekend!",
        ],
      },
    },
    {
      id: "ubud",
      label: "Ubud",
      image: "Bali_rice_terraces.jpg",
      deco: "06",
      nights: "12 – 16 Jul · 4 nights · jungle villa",
      title: "Ubud",
      body: "A secluded villa in the jungle, rice-terrace views, well outside the busy centre. This is where we breathe.",
      bullets: [
        "🌋 Mt Batur sunrise trek (~14 Jul)",
        "💦 A private waterfall at first light",
        "🌾 Tegallalang terraces at dawn, before the crowds",
        "💆 A couples' spa day — the real reset",
      ],
    },
    {
      id: "munduk",
      label: "Munduk",
      image: "Pura_Ulun_Danu_Tamblingan,_Munduk.jpg",
      deco: "07",
      nights: "16 – 18 Jul · 2 nights",
      title: "Munduk",
      body: "Cool mountain air, mist and waterfalls. The most *nobody else around* stretch of the trip.",
      bullets: [
        "🚣 Sunrise paddle on the Twin Lakes",
        "💦 Waterfall hikes minutes from the door",
        "☕ A walk through a working coffee plantation",
      ],
    },
    {
      id: "sanur",
      label: "Sanur",
      image: "Sanur_Beach.JPG",
      deco: "08",
      nights: "18 – 20 Jul · the soft landing",
      title: "Sanur 🎂",
      body: "We arrive on *my birthday* via a scenic drive down from the mountains. No agenda — just this.",
      bullets: [
        "🌅 A sunrise beach walk (Sanur faces east — rare in Bali)",
        "🕯️ A quiet candlelit birthday dinner, nowhere to be",
        "⛵ Maybe a day boat back to Lembongan — a callback to week one",
      ],
      note: "Fly home 20 Jul",
    },
    {
      id: "close",
      label: "Verdict",
      eyebrow: "So… what do you think?",
      title: "Are we doing this?",
      body: "Nothing's locked. This is the *skeleton* — the bones are good. Tell me where you're at.",
      hypeMeter: true,
      note: "Two things I actually need from you: the **manta/snorkel** call and the **Amed** call. Everything else we shape together.",
    },
  ],
};
